application:
  appId: 10
  appKey: '223323'
  appName: 'appName'
  httpPort: 9090
databases:
  dbMonitor:
    dsn: 'sqlserver://plf_user:2KspR9JQw@10.250.60.245:1433?database=BenlaiMonitorNew&connection+timeout=30'
    driver: 'mssql'
    useDbms: false
    logConfig:
      slowThresholdMS: 1000
      level: 'debug'
redis:
  testRedis:
    addr: '10.250.60.11:6379'
zookeeper:
  trunk-zk:
    servers: 10.250.60.95:2181;10.250.60.95:2181
  branche-zk:
    servers: 10.250.60.95:2181,10.250.60.95:2181
  branch-zk:
    servers: 10.250.60.95:2181
logger:
  type: 'zap'
  Level: 'debug'
extend:
  jenkins:
    p2c-api: 'p2c-api-test'
    p2c-erp: 'p2c-erp-test'